name: Requirements

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  requirements:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.11
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y python3-dev graphviz libgraphviz-dev pkg-config
      - run: make setup-dev

      - name: Generate requirements.txt
        run: make export-requirements

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update requirements.txt"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
