name: Test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.11
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y python3-dev graphviz libgraphviz-dev pkg-config
      - run: make setup-dev
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Export token as env variable
        run: echo "ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }}" >> $GITHUB_ENV
      - run: make test